// قاعدة بيانات الأطعمة — القيم الغذائية لكل 100 جرام
// المصادر: قواعد بيانات USDA وجداول تركيب الأغذية المصرية (قيم تقريبية للاسترشاد)
// kcal: سعرات، protein/carbs/fat/fiber: جم، ca/fe/zn/vitC: مجم، vitA/vitD: ميكروجرام

const FOOD_CATEGORIES = [
  { id: "starch", name: "نشويات وخبز" },
  { id: "protein", name: "لحوم وبروتينات" },
  { id: "legume", name: "بقوليات" },
  { id: "dairy", name: "ألبان وأجبان" },
  { id: "veg", name: "خضروات" },
  { id: "fruit", name: "فواكه" },
  { id: "fat", name: "دهون ومكسرات" },
  { id: "drink", name: "مشروبات وعصائر" },
  { id: "sweet", name: "حلويات وسكريات" },
  { id: "soup", name: "شوربة وأطباق" },
];

const FOODS = [
  // ===== نشويات وخبز =====
  { id: "baladi-bread", name: "عيش بلدي", cat: "starch", kcal: 255, protein: 8.5, carbs: 52, fat: 1.2, fiber: 4.5, ca: 45, fe: 2.5, zn: 1.2, vitA: 0, vitC: 0, vitD: 0,
    units: [ { name: "ربع رغيف", grams: 22 }, { name: "نصف رغيف", grams: 45 }, { name: "رغيف كامل", grams: 90 } ] },
  { id: "fino-bread", name: "عيش فينو", cat: "starch", kcal: 270, protein: 8, carbs: 54, fat: 2.5, fiber: 2.2, ca: 30, fe: 2.2, zn: 0.8, vitA: 0, vitC: 0, vitD: 0,
    units: [ { name: "نصف رغيف", grams: 30 }, { name: "رغيف", grams: 60 } ] },
  { id: "toast-bread", name: "توست", cat: "starch", kcal: 265, protein: 9, carbs: 49, fat: 3.2, fiber: 2.7, ca: 60, fe: 2.8, zn: 0.9, vitA: 0, vitC: 0, vitD: 0,
    units: [ { name: "شريحة", grams: 25 } ] },
  { id: "rice-cooked", name: "أرز أبيض مطبوخ", cat: "starch", kcal: 150, protein: 2.7, carbs: 32, fat: 1.5, fiber: 0.4, ca: 10, fe: 0.5, zn: 0.5, vitA: 0, vitC: 0, vitD: 0,
    units: [ { name: "ملعقة كبيرة", grams: 20 }, { name: "نصف كوب", grams: 90 }, { name: "كوب", grams: 180 } ] },
  { id: "pasta-cooked", name: "مكرونة مسلوقة", cat: "starch", kcal: 158, protein: 5.8, carbs: 31, fat: 0.9, fiber: 1.8, ca: 7, fe: 1.3, zn: 0.7, vitA: 0, vitC: 0, vitD: 0,
    units: [ { name: "ملعقة كبيرة", grams: 20 }, { name: "نصف كوب", grams: 70 }, { name: "كوب", grams: 140 } ] },
  { id: "potato-boiled", name: "بطاطس مسلوقة", cat: "starch", kcal: 87, protein: 1.9, carbs: 20, fat: 0.1, fiber: 1.8, ca: 5, fe: 0.3, zn: 0.3, vitA: 0, vitC: 13, vitD: 0,
    units: [ { name: "حبة صغيرة", grams: 100 }, { name: "حبة متوسطة", grams: 150 } ] },
  { id: "potato-mashed", name: "بطاطس بوريه (باللبن)", cat: "starch", kcal: 105, protein: 2.5, carbs: 17, fat: 3, fiber: 1.5, ca: 25, fe: 0.3, zn: 0.4, vitA: 25, vitC: 10, vitD: 0.2,
    units: [ { name: "ملعقة كبيرة", grams: 25 }, { name: "نصف كوب", grams: 105 }, { name: "كوب", grams: 210 } ] },
  { id: "sweet-potato", name: "بطاطا مشوية", cat: "starch", kcal: 90, protein: 2, carbs: 21, fat: 0.2, fiber: 3.3, ca: 38, fe: 0.7, zn: 0.3, vitA: 960, vitC: 20, vitD: 0,
    units: [ { name: "نصف حبة", grams: 75 }, { name: "حبة متوسطة", grams: 150 } ] },
  { id: "oats", name: "شوفان (بالماء)", cat: "starch", kcal: 71, protein: 2.5, carbs: 12, fat: 1.5, fiber: 1.7, ca: 9, fe: 0.9, zn: 0.6, vitA: 0, vitC: 0, vitD: 0,
    units: [ { name: "ملعقة كبيرة", grams: 15 }, { name: "نصف كوب", grams: 120 }, { name: "كوب", grams: 240 } ] },
  { id: "belila", name: "بليلة باللبن", cat: "starch", kcal: 115, protein: 4.5, carbs: 20, fat: 2, fiber: 1.8, ca: 80, fe: 0.8, zn: 0.7, vitA: 30, vitC: 0, vitD: 0.3,
    units: [ { name: "نصف كوب", grams: 120 }, { name: "كوب", grams: 240 } ] },
  { id: "couscous", name: "كسكسي مطبوخ", cat: "starch", kcal: 112, protein: 3.8, carbs: 23, fat: 0.2, fiber: 1.4, ca: 8, fe: 0.4, zn: 0.3, vitA: 0, vitC: 0, vitD: 0,
    units: [ { name: "نصف كوب", grams: 80 }, { name: "كوب", grams: 160 } ] },
  { id: "freekeh", name: "فريك مطبوخ", cat: "starch", kcal: 130, protein: 5, carbs: 26, fat: 1, fiber: 4.5, ca: 25, fe: 1.5, zn: 1.5, vitA: 0, vitC: 0, vitD: 0,
    units: [ { name: "نصف كوب", grams: 90 }, { name: "كوب", grams: 180 } ] },

  // ===== لحوم وبروتينات =====
  { id: "egg-boiled", name: "بيضة مسلوقة", cat: "protein", kcal: 155, protein: 13, carbs: 1.1, fat: 11, fiber: 0, ca: 50, fe: 1.2, zn: 1.3, vitA: 160, vitC: 0, vitD: 2,
    units: [ { name: "بيضة", grams: 50 } ] },
  { id: "egg-fried", name: "بيض مقلي", cat: "protein", kcal: 196, protein: 13, carbs: 1, fat: 15, fiber: 0, ca: 55, fe: 1.9, zn: 1.4, vitA: 190, vitC: 0, vitD: 2.2,
    units: [ { name: "بيضة", grams: 55 } ] },
  { id: "chicken-breast", name: "صدور فراخ مطبوخة", cat: "protein", kcal: 165, protein: 31, carbs: 0, fat: 3.6, fiber: 0, ca: 15, fe: 1, zn: 1, vitA: 6, vitC: 0, vitD: 0.1,
    units: [ { name: "قطعة صغيرة", grams: 60 }, { name: "قطعة متوسطة", grams: 100 }, { name: "ربع فرخة", grams: 180 } ] },
  { id: "chicken-thigh", name: "ورك فراخ مطبوخ", cat: "protein", kcal: 209, protein: 26, carbs: 0, fat: 11, fiber: 0, ca: 12, fe: 1.3, zn: 2.4, vitA: 20, vitC: 0, vitD: 0.1,
    units: [ { name: "قطعة", grams: 100 } ] },
  { id: "beef-cooked", name: "لحمة بقري مطبوخة", cat: "protein", kcal: 250, protein: 26, carbs: 0, fat: 15, fiber: 0, ca: 18, fe: 2.6, zn: 6, vitA: 0, vitC: 0, vitD: 0.1,
    units: [ { name: "قطعة صغيرة", grams: 50 }, { name: "قطعة متوسطة", grams: 90 } ] },
  { id: "minced-meat", name: "لحمة مفرومة مطبوخة", cat: "protein", kcal: 240, protein: 24, carbs: 0, fat: 16, fiber: 0, ca: 20, fe: 2.4, zn: 5.5, vitA: 0, vitC: 0, vitD: 0.1,
    units: [ { name: "ملعقة كبيرة", grams: 25 }, { name: "نصف كوب", grams: 80 } ] },
  { id: "kofta", name: "كفتة مشوية", cat: "protein", kcal: 260, protein: 20, carbs: 4, fat: 18, fiber: 0.5, ca: 30, fe: 2.2, zn: 4.5, vitA: 10, vitC: 1, vitD: 0.1,
    units: [ { name: "صباع", grams: 40 } ] },
  { id: "liver", name: "كبدة مطبوخة", cat: "protein", kcal: 175, protein: 26, carbs: 4, fat: 5, fiber: 0, ca: 10, fe: 6.5, zn: 5.3, vitA: 9400, vitC: 2, vitD: 1.2,
    units: [ { name: "ملعقة كبيرة", grams: 25 }, { name: "قطعة متوسطة", grams: 80 } ] },
  { id: "fish-grilled", name: "سمك مشوي (بلطي)", cat: "protein", kcal: 128, protein: 26, carbs: 0, fat: 2.7, fiber: 0, ca: 14, fe: 0.7, zn: 0.4, vitA: 0, vitC: 0, vitD: 3.1,
    units: [ { name: "قطعة صغيرة", grams: 60 }, { name: "سمكة متوسطة", grams: 150 } ] },
  { id: "fish-fried", name: "سمك مقلي", cat: "protein", kcal: 200, protein: 22, carbs: 7, fat: 9, fiber: 0.3, ca: 20, fe: 0.8, zn: 0.5, vitA: 5, vitC: 0, vitD: 2.5,
    units: [ { name: "قطعة", grams: 100 } ] },
  { id: "tuna", name: "تونة (مصفاة)", cat: "protein", kcal: 130, protein: 26, carbs: 0, fat: 2.5, fiber: 0, ca: 12, fe: 1.3, zn: 0.8, vitA: 17, vitC: 0, vitD: 1.7,
    units: [ { name: "ملعقة كبيرة", grams: 25 }, { name: "نصف علبة", grams: 70 }, { name: "علبة", grams: 140 } ] },
  { id: "sardines", name: "سردين", cat: "protein", kcal: 208, protein: 25, carbs: 0, fat: 11, fiber: 0, ca: 380, fe: 2.9, zn: 1.3, vitA: 32, vitC: 0, vitD: 4.8,
    units: [ { name: "سمكة", grams: 25 }, { name: "نصف علبة", grams: 60 } ] },
  { id: "shrimp", name: "جمبري مطبوخ", cat: "protein", kcal: 99, protein: 24, carbs: 0.2, fat: 0.3, fiber: 0, ca: 70, fe: 0.5, zn: 1.6, vitA: 54, vitC: 0, vitD: 0.1,
    units: [ { name: "5 حبات", grams: 50 } ] },
  { id: "turkey-slices", name: "شرائح ديك رومي (لانشون)", cat: "protein", kcal: 110, protein: 17, carbs: 2, fat: 3.5, fiber: 0, ca: 10, fe: 1, zn: 1.5, vitA: 0, vitC: 0, vitD: 0.2,
    units: [ { name: "شريحة", grams: 20 } ] },

  // ===== بقوليات =====
  { id: "foul", name: "فول مدمس", cat: "legume", kcal: 110, protein: 7.6, carbs: 18, fat: 0.6, fiber: 5.2, ca: 40, fe: 1.9, zn: 1, vitA: 1, vitC: 0.5, vitD: 0,
    units: [ { name: "ملعقة كبيرة", grams: 25 }, { name: "نصف كوب", grams: 85 }, { name: "طبق صغير", grams: 170 } ] },
  { id: "falafel", name: "طعمية", cat: "legume", kcal: 330, protein: 13, carbs: 30, fat: 18, fiber: 5, ca: 55, fe: 3.4, zn: 1.5, vitA: 1, vitC: 2, vitD: 0,
    units: [ { name: "قرص", grams: 25 } ] },
  { id: "lentils-cooked", name: "عدس مطبوخ", cat: "legume", kcal: 116, protein: 9, carbs: 20, fat: 0.4, fiber: 7.9, ca: 19, fe: 3.3, zn: 1.3, vitA: 0, vitC: 1.5, vitD: 0,
    units: [ { name: "ملعقة كبيرة", grams: 25 }, { name: "نصف كوب", grams: 100 }, { name: "كوب", grams: 200 } ] },
  { id: "lentil-soup", name: "شوربة عدس", cat: "legume", kcal: 70, protein: 4.5, carbs: 11, fat: 1, fiber: 3.5, ca: 15, fe: 1.8, zn: 0.7, vitA: 60, vitC: 2, vitD: 0,
    units: [ { name: "نصف كوب", grams: 120 }, { name: "طبق", grams: 250 } ] },
  { id: "chickpeas", name: "حمص مطبوخ", cat: "legume", kcal: 164, protein: 8.9, carbs: 27, fat: 2.6, fiber: 7.6, ca: 49, fe: 2.9, zn: 1.5, vitA: 1, vitC: 1.3, vitD: 0,
    units: [ { name: "ملعقة كبيرة", grams: 20 }, { name: "نصف كوب", grams: 80 } ] },
  { id: "hummus-dip", name: "حمص بالطحينة", cat: "legume", kcal: 170, protein: 7.9, carbs: 14, fat: 9.6, fiber: 6, ca: 38, fe: 2.4, zn: 1.8, vitA: 0, vitC: 0, vitD: 0,
    units: [ { name: "ملعقة كبيرة", grams: 15 }, { name: "ربع كوب", grams: 60 } ] },
  { id: "white-beans", name: "فاصوليا بيضاء مطبوخة", cat: "legume", kcal: 120, protein: 7, carbs: 20, fat: 1.5, fiber: 5.5, ca: 60, fe: 2.5, zn: 1.2, vitA: 30, vitC: 3, vitD: 0,
    units: [ { name: "نصف كوب", grams: 90 }, { name: "طبق", grams: 200 } ] },
  { id: "peas-cooked", name: "بسلة مطبوخة", cat: "legume", kcal: 84, protein: 5.4, carbs: 15, fat: 0.4, fiber: 5.5, ca: 27, fe: 1.5, zn: 1.2, vitA: 40, vitC: 14, vitD: 0,
    units: [ { name: "ملعقة كبيرة", grams: 20 }, { name: "نصف كوب", grams: 80 } ] },

  // ===== ألبان وأجبان =====
  { id: "milk-full", name: "لبن كامل الدسم", cat: "dairy", kcal: 61, protein: 3.2, carbs: 4.8, fat: 3.3, fiber: 0, ca: 113, fe: 0, zn: 0.4, vitA: 46, vitC: 0, vitD: 1.3,
    units: [ { name: "نصف كوب", grams: 120 }, { name: "كوب", grams: 240 } ] },
  { id: "milk-fortified", name: "لبن مدعم بفيتامين د", cat: "dairy", kcal: 61, protein: 3.2, carbs: 4.8, fat: 3.3, fiber: 0, ca: 120, fe: 0, zn: 0.4, vitA: 60, vitC: 0, vitD: 2.5,
    units: [ { name: "نصف كوب", grams: 120 }, { name: "كوب", grams: 240 } ] },
  { id: "yogurt", name: "زبادي", cat: "dairy", kcal: 61, protein: 3.5, carbs: 4.7, fat: 3.3, fiber: 0, ca: 121, fe: 0.1, zn: 0.6, vitA: 27, vitC: 0.5, vitD: 0.1,
    units: [ { name: "نصف علبة", grams: 55 }, { name: "علبة", grams: 110 } ] },
  { id: "greek-yogurt", name: "زبادي يوناني", cat: "dairy", kcal: 97, protein: 9, carbs: 3.9, fat: 5, fiber: 0, ca: 110, fe: 0, zn: 0.5, vitA: 26, vitC: 0, vitD: 0.1,
    units: [ { name: "نصف علبة", grams: 75 }, { name: "علبة", grams: 150 } ] },
  { id: "cottage-cheese", name: "جبنة قريش", cat: "dairy", kcal: 98, protein: 11, carbs: 3.4, fat: 4.3, fiber: 0, ca: 83, fe: 0.1, zn: 0.4, vitA: 37, vitC: 0, vitD: 0.1,
    units: [ { name: "ملعقة كبيرة", grams: 30 }, { name: "قطعة", grams: 100 } ] },
  { id: "white-cheese", name: "جبنة بيضاء (فيتا)", cat: "dairy", kcal: 264, protein: 14, carbs: 4, fat: 21, fiber: 0, ca: 493, fe: 0.7, zn: 2.9, vitA: 125, vitC: 0, vitD: 0.4,
    units: [ { name: "ملعقة كبيرة", grams: 20 }, { name: "قطعة", grams: 40 } ] },
  { id: "rumi-cheese", name: "جبنة رومي", cat: "dairy", kcal: 380, protein: 25, carbs: 2, fat: 30, fiber: 0, ca: 720, fe: 0.4, zn: 3.1, vitA: 240, vitC: 0, vitD: 0.5,
    units: [ { name: "شريحة", grams: 20 } ] },
  { id: "cheese-triangle", name: "جبنة مثلثات", cat: "dairy", kcal: 240, protein: 9, carbs: 6, fat: 20, fiber: 0, ca: 350, fe: 0.2, zn: 2, vitA: 180, vitC: 0, vitD: 0.3,
    units: [ { name: "مثلث", grams: 17 } ] },
  { id: "rice-pudding", name: "أرز باللبن", cat: "dairy", kcal: 120, protein: 3.3, carbs: 21, fat: 2.5, fiber: 0.2, ca: 90, fe: 0.2, zn: 0.4, vitA: 30, vitC: 0, vitD: 0.3,
    units: [ { name: "نصف علبة", grams: 75 }, { name: "علبة", grams: 150 } ] },
  { id: "mehalabeya", name: "مهلبية", cat: "dairy", kcal: 110, protein: 3, carbs: 19, fat: 2.5, fiber: 0.1, ca: 85, fe: 0.1, zn: 0.3, vitA: 28, vitC: 0, vitD: 0.3,
    units: [ { name: "نصف علبة", grams: 75 }, { name: "علبة", grams: 150 } ] },

  // ===== خضروات =====
  { id: "molokhia", name: "ملوخية مطبوخة", cat: "veg", kcal: 60, protein: 3, carbs: 8, fat: 2, fiber: 3.5, ca: 200, fe: 3.2, zn: 0.6, vitA: 450, vitC: 25, vitD: 0,
    units: [ { name: "نصف كوب", grams: 120 }, { name: "طبق", grams: 250 } ] },
  { id: "spinach-cooked", name: "سبانخ مطبوخة", cat: "veg", kcal: 41, protein: 3, carbs: 5, fat: 1.5, fiber: 2.4, ca: 136, fe: 3.6, zn: 0.8, vitA: 524, vitC: 10, vitD: 0,
    units: [ { name: "نصف كوب", grams: 90 }, { name: "طبق", grams: 200 } ] },
  { id: "zucchini-cooked", name: "كوسة مطبوخة", cat: "veg", kcal: 30, protein: 1.1, carbs: 5, fat: 1, fiber: 1.2, ca: 20, fe: 0.4, zn: 0.3, vitA: 28, vitC: 12, vitD: 0,
    units: [ { name: "حبة", grams: 80 }, { name: "نصف كوب", grams: 90 } ] },
  { id: "carrots", name: "جزر", cat: "veg", kcal: 41, protein: 0.9, carbs: 10, fat: 0.2, fiber: 2.8, ca: 33, fe: 0.3, zn: 0.2, vitA: 835, vitC: 6, vitD: 0,
    units: [ { name: "حبة صغيرة", grams: 50 }, { name: "حبة متوسطة", grams: 80 } ] },
  { id: "green-beans", name: "فاصوليا خضراء مطبوخة", cat: "veg", kcal: 45, protein: 2, carbs: 8, fat: 1, fiber: 3.2, ca: 45, fe: 1, zn: 0.3, vitA: 35, vitC: 10, vitD: 0,
    units: [ { name: "نصف كوب", grams: 80 }, { name: "طبق", grams: 180 } ] },
  { id: "okra", name: "بامية مطبوخة", cat: "veg", kcal: 55, protein: 2, carbs: 8, fat: 2, fiber: 3.2, ca: 80, fe: 0.6, zn: 0.5, vitA: 36, vitC: 16, vitD: 0,
    units: [ { name: "نصف كوب", grams: 90 }, { name: "طبق", grams: 200 } ] },
  { id: "tomato", name: "طماطم", cat: "veg", kcal: 18, protein: 0.9, carbs: 3.9, fat: 0.2, fiber: 1.2, ca: 10, fe: 0.3, zn: 0.2, vitA: 42, vitC: 14, vitD: 0,
    units: [ { name: "حبة صغيرة", grams: 90 }, { name: "حبة متوسطة", grams: 120 } ] },
  { id: "cucumber", name: "خيار", cat: "veg", kcal: 15, protein: 0.7, carbs: 3.6, fat: 0.1, fiber: 0.5, ca: 16, fe: 0.3, zn: 0.2, vitA: 5, vitC: 2.8, vitD: 0,
    units: [ { name: "حبة", grams: 100 } ] },
  { id: "peppers", name: "فلفل ألوان", cat: "veg", kcal: 31, protein: 1, carbs: 6, fat: 0.3, fiber: 2.1, ca: 7, fe: 0.4, zn: 0.3, vitA: 157, vitC: 128, vitD: 0,
    units: [ { name: "نصف حبة", grams: 60 }, { name: "حبة", grams: 120 } ] },
  { id: "broccoli", name: "بروكلي مطبوخ", cat: "veg", kcal: 35, protein: 2.4, carbs: 7, fat: 0.4, fiber: 3.3, ca: 40, fe: 0.7, zn: 0.5, vitA: 77, vitC: 65, vitD: 0,
    units: [ { name: "نصف كوب", grams: 80 }, { name: "كوب", grams: 160 } ] },
  { id: "cauliflower", name: "قرنبيط مطبوخ", cat: "veg", kcal: 40, protein: 1.8, carbs: 4.1, fat: 2, fiber: 2.3, ca: 16, fe: 0.3, zn: 0.2, vitA: 1, vitC: 44, vitD: 0,
    units: [ { name: "نصف كوب", grams: 65 }, { name: "كوب", grams: 130 } ] },
  { id: "eggplant-cooked", name: "باذنجان مطبوخ", cat: "veg", kcal: 60, protein: 1, carbs: 8, fat: 3, fiber: 2.5, ca: 9, fe: 0.3, zn: 0.2, vitA: 2, vitC: 1.3, vitD: 0,
    units: [ { name: "نصف كوب", grams: 80 } ] },
  { id: "beets", name: "بنجر مسلوق", cat: "veg", kcal: 44, protein: 1.7, carbs: 10, fat: 0.2, fiber: 2, ca: 16, fe: 0.8, zn: 0.4, vitA: 2, vitC: 3.6, vitD: 0,
    units: [ { name: "حبة صغيرة", grams: 80 } ] },
  { id: "salad-mixed", name: "سلطة خضراء", cat: "veg", kcal: 20, protein: 1, carbs: 4, fat: 0.2, fiber: 1.5, ca: 20, fe: 0.5, zn: 0.2, vitA: 100, vitC: 12, vitD: 0,
    units: [ { name: "طبق صغير", grams: 100 }, { name: "طبق كبير", grams: 200 } ] },
  { id: "mashed-veg", name: "خضار مهروس (مشكل)", cat: "veg", kcal: 45, protein: 1.5, carbs: 8, fat: 1, fiber: 2.5, ca: 30, fe: 0.6, zn: 0.3, vitA: 300, vitC: 15, vitD: 0,
    units: [ { name: "ملعقة كبيرة", grams: 25 }, { name: "نصف كوب", grams: 100 }, { name: "كوب", grams: 200 } ] },

  // ===== فواكه =====
  { id: "banana", name: "موز", cat: "fruit", kcal: 89, protein: 1.1, carbs: 23, fat: 0.3, fiber: 2.6, ca: 5, fe: 0.3, zn: 0.2, vitA: 3, vitC: 8.7, vitD: 0,
    units: [ { name: "نصف موزة", grams: 50 }, { name: "موزة متوسطة", grams: 100 } ] },
  { id: "apple", name: "تفاح", cat: "fruit", kcal: 52, protein: 0.3, carbs: 14, fat: 0.2, fiber: 2.4, ca: 6, fe: 0.1, zn: 0, vitA: 3, vitC: 4.6, vitD: 0,
    units: [ { name: "نصف تفاحة", grams: 80 }, { name: "تفاحة متوسطة", grams: 160 } ] },
  { id: "orange", name: "برتقال", cat: "fruit", kcal: 47, protein: 0.9, carbs: 12, fat: 0.1, fiber: 2.4, ca: 40, fe: 0.1, zn: 0.1, vitA: 11, vitC: 53, vitD: 0,
    units: [ { name: "برتقالة متوسطة", grams: 130 } ] },
  { id: "guava", name: "جوافة", cat: "fruit", kcal: 68, protein: 2.6, carbs: 14, fat: 1, fiber: 5.4, ca: 18, fe: 0.3, zn: 0.2, vitA: 31, vitC: 228, vitD: 0,
    units: [ { name: "حبة", grams: 100 } ] },
  { id: "dates", name: "بلح/تمر", cat: "fruit", kcal: 277, protein: 1.8, carbs: 75, fat: 0.2, fiber: 6.7, ca: 64, fe: 0.9, zn: 0.4, vitA: 7, vitC: 0, vitD: 0,
    units: [ { name: "حبة", grams: 10 }, { name: "3 حبات", grams: 30 } ] },
  { id: "grapes", name: "عنب", cat: "fruit", kcal: 69, protein: 0.7, carbs: 18, fat: 0.2, fiber: 0.9, ca: 10, fe: 0.4, zn: 0.1, vitA: 3, vitC: 3.2, vitD: 0,
    units: [ { name: "10 حبات", grams: 50 }, { name: "كوب", grams: 150 } ] },
  { id: "mango", name: "مانجو", cat: "fruit", kcal: 60, protein: 0.8, carbs: 15, fat: 0.4, fiber: 1.6, ca: 11, fe: 0.2, zn: 0.1, vitA: 54, vitC: 36, vitD: 0,
    units: [ { name: "نصف حبة", grams: 100 }, { name: "حبة", grams: 200 } ] },
  { id: "watermelon", name: "بطيخ", cat: "fruit", kcal: 30, protein: 0.6, carbs: 8, fat: 0.2, fiber: 0.4, ca: 7, fe: 0.2, zn: 0.1, vitA: 28, vitC: 8, vitD: 0,
    units: [ { name: "شريحة", grams: 150 }, { name: "كوب مكعبات", grams: 150 } ] },
  { id: "strawberry", name: "فراولة", cat: "fruit", kcal: 32, protein: 0.7, carbs: 7.7, fat: 0.3, fiber: 2, ca: 16, fe: 0.4, zn: 0.1, vitA: 1, vitC: 59, vitD: 0,
    units: [ { name: "5 حبات", grams: 60 }, { name: "كوب", grams: 150 } ] },
  { id: "pear", name: "كمثرى", cat: "fruit", kcal: 57, protein: 0.4, carbs: 15, fat: 0.1, fiber: 3.1, ca: 9, fe: 0.2, zn: 0.1, vitA: 1, vitC: 4.3, vitD: 0,
    units: [ { name: "حبة متوسطة", grams: 150 } ] },
  { id: "apricot", name: "مشمش", cat: "fruit", kcal: 48, protein: 1.4, carbs: 11, fat: 0.4, fiber: 2, ca: 13, fe: 0.4, zn: 0.2, vitA: 96, vitC: 10, vitD: 0,
    units: [ { name: "حبة", grams: 35 }, { name: "3 حبات", grams: 105 } ] },
  { id: "raisins", name: "زبيب", cat: "fruit", kcal: 299, protein: 3.1, carbs: 79, fat: 0.5, fiber: 3.7, ca: 50, fe: 1.9, zn: 0.2, vitA: 0, vitC: 2.3, vitD: 0,
    units: [ { name: "ملعقة كبيرة", grams: 10 } ] },
  { id: "fruit-mashed", name: "فواكه مهروسة", cat: "fruit", kcal: 65, protein: 0.7, carbs: 16, fat: 0.2, fiber: 2, ca: 10, fe: 0.3, zn: 0.1, vitA: 20, vitC: 20, vitD: 0,
    units: [ { name: "ملعقة كبيرة", grams: 20 }, { name: "نصف كوب", grams: 100 } ] },

  // ===== دهون ومكسرات =====
  { id: "olive-oil", name: "زيت زيتون", cat: "fat", kcal: 884, protein: 0, carbs: 0, fat: 100, fiber: 0, ca: 1, fe: 0.6, zn: 0, vitA: 0, vitC: 0, vitD: 0,
    units: [ { name: "ملعقة صغيرة", grams: 5 }, { name: "ملعقة كبيرة", grams: 14 } ] },
  { id: "butter", name: "زبدة", cat: "fat", kcal: 717, protein: 0.9, carbs: 0.1, fat: 81, fiber: 0, ca: 24, fe: 0, zn: 0.1, vitA: 684, vitC: 0, vitD: 1.5,
    units: [ { name: "ملعقة صغيرة", grams: 5 }, { name: "ملعقة كبيرة", grams: 14 } ] },
  { id: "tahini", name: "طحينة", cat: "fat", kcal: 595, protein: 17, carbs: 21, fat: 54, fiber: 9.3, ca: 426, fe: 9, zn: 4.6, vitA: 3, vitC: 0, vitD: 0,
    units: [ { name: "ملعقة صغيرة", grams: 7 }, { name: "ملعقة كبيرة", grams: 15 } ] },
  { id: "peanut-butter", name: "زبدة فول سوداني", cat: "fat", kcal: 588, protein: 25, carbs: 20, fat: 50, fiber: 6, ca: 49, fe: 1.9, zn: 2.9, vitA: 0, vitC: 0, vitD: 0,
    units: [ { name: "ملعقة صغيرة", grams: 8 }, { name: "ملعقة كبيرة", grams: 16 } ] },
  { id: "walnuts", name: "عين جمل مطحون", cat: "fat", kcal: 654, protein: 15, carbs: 14, fat: 65, fiber: 6.7, ca: 98, fe: 2.9, zn: 3.1, vitA: 1, vitC: 1.3, vitD: 0,
    units: [ { name: "ملعقة كبيرة", grams: 8 }, { name: "حفنة صغيرة", grams: 15 } ] },
  { id: "almonds", name: "لوز مطحون", cat: "fat", kcal: 579, protein: 21, carbs: 22, fat: 50, fiber: 12.5, ca: 269, fe: 3.7, zn: 3.1, vitA: 0, vitC: 0, vitD: 0,
    units: [ { name: "ملعقة كبيرة", grams: 8 }, { name: "حفنة صغيرة", grams: 15 } ] },
  { id: "avocado", name: "أفوكادو", cat: "fat", kcal: 160, protein: 2, carbs: 8.5, fat: 15, fiber: 6.7, ca: 12, fe: 0.6, zn: 0.6, vitA: 7, vitC: 10, vitD: 0,
    units: [ { name: "ربع حبة", grams: 50 }, { name: "نصف حبة", grams: 100 } ] },

  // ===== مشروبات وعصائر =====
  { id: "orange-juice", name: "عصير برتقال طازج", cat: "drink", kcal: 45, protein: 0.7, carbs: 10, fat: 0.2, fiber: 0.2, ca: 11, fe: 0.2, zn: 0, vitA: 10, vitC: 50, vitD: 0,
    units: [ { name: "نصف كوب", grams: 120 }, { name: "كوب", grams: 240 } ] },
  { id: "mango-juice", name: "عصير مانجو", cat: "drink", kcal: 60, protein: 0.4, carbs: 15, fat: 0.2, fiber: 0.5, ca: 10, fe: 0.2, zn: 0, vitA: 30, vitC: 25, vitD: 0,
    units: [ { name: "نصف كوب", grams: 120 }, { name: "كوب", grams: 240 } ] },
  { id: "guava-juice", name: "عصير جوافة", cat: "drink", kcal: 55, protein: 0.5, carbs: 13, fat: 0.2, fiber: 1.5, ca: 12, fe: 0.2, zn: 0.1, vitA: 15, vitC: 100, vitD: 0,
    units: [ { name: "نصف كوب", grams: 120 }, { name: "كوب", grams: 240 } ] },
  { id: "banana-milk", name: "لبن بالموز (ميلك شيك)", cat: "drink", kcal: 80, protein: 2.5, carbs: 13, fat: 2, fiber: 0.8, ca: 75, fe: 0.2, zn: 0.3, vitA: 30, vitC: 4, vitD: 0.8,
    units: [ { name: "نصف كوب", grams: 125 }, { name: "كوب", grams: 250 } ] },
  { id: "date-milk", name: "لبن بالتمر", cat: "drink", kcal: 95, protein: 2.8, carbs: 17, fat: 2.2, fiber: 1, ca: 85, fe: 0.3, zn: 0.3, vitA: 32, vitC: 0, vitD: 0.8,
    units: [ { name: "نصف كوب", grams: 125 }, { name: "كوب", grams: 250 } ] },
  { id: "cocoa-milk", name: "كاكاو باللبن", cat: "drink", kcal: 83, protein: 3.2, carbs: 11, fat: 3, fiber: 0.7, ca: 100, fe: 0.4, zn: 0.5, vitA: 40, vitC: 0, vitD: 1,
    units: [ { name: "نصف كوب", grams: 125 }, { name: "كوب", grams: 250 } ] },
  { id: "anise-tea", name: "ينسون/كراوية", cat: "drink", kcal: 5, protein: 0.1, carbs: 1, fat: 0, fiber: 0.1, ca: 5, fe: 0.2, zn: 0, vitA: 0, vitC: 0, vitD: 0,
    units: [ { name: "كوب", grams: 200 } ] },

  // ===== حلويات وسكريات =====
  { id: "honey", name: "عسل نحل", cat: "sweet", kcal: 304, protein: 0.3, carbs: 82, fat: 0, fiber: 0.2, ca: 6, fe: 0.4, zn: 0.2, vitA: 0, vitC: 0.5, vitD: 0,
    units: [ { name: "ملعقة صغيرة", grams: 7 }, { name: "ملعقة كبيرة", grams: 21 } ] },
  { id: "molasses", name: "عسل أسود", cat: "sweet", kcal: 290, protein: 0, carbs: 75, fat: 0.1, fiber: 0, ca: 205, fe: 4.7, zn: 0.3, vitA: 0, vitC: 0, vitD: 0,
    units: [ { name: "ملعقة صغيرة", grams: 7 }, { name: "ملعقة كبيرة", grams: 21 } ] },
  { id: "halawa", name: "حلاوة طحينية", cat: "sweet", kcal: 520, protein: 12, carbs: 55, fat: 30, fiber: 4.5, ca: 90, fe: 3.5, zn: 2.5, vitA: 0, vitC: 0, vitD: 0,
    units: [ { name: "ملعقة كبيرة", grams: 20 }, { name: "قطعة", grams: 40 } ] },
  { id: "jam", name: "مربى", cat: "sweet", kcal: 270, protein: 0.4, carbs: 69, fat: 0.1, fiber: 1, ca: 20, fe: 0.5, zn: 0, vitA: 2, vitC: 9, vitD: 0,
    units: [ { name: "ملعقة صغيرة", grams: 7 }, { name: "ملعقة كبيرة", grams: 20 } ] },
  { id: "biscuits", name: "بسكويت سادة", cat: "sweet", kcal: 460, protein: 6.5, carbs: 72, fat: 16, fiber: 1.7, ca: 25, fe: 2, zn: 0.6, vitA: 0, vitC: 0, vitD: 0,
    units: [ { name: "قطعة", grams: 8 }, { name: "3 قطع", grams: 24 } ] },
  { id: "cake-plain", name: "كيك سادة", cat: "sweet", kcal: 350, protein: 5, carbs: 55, fat: 12, fiber: 0.8, ca: 60, fe: 1.2, zn: 0.4, vitA: 60, vitC: 0, vitD: 0.4,
    units: [ { name: "قطعة صغيرة", grams: 40 }, { name: "قطعة", grams: 70 } ] },
  { id: "basbousa", name: "بسبوسة", cat: "sweet", kcal: 380, protein: 4.5, carbs: 58, fat: 15, fiber: 1, ca: 55, fe: 0.8, zn: 0.5, vitA: 40, vitC: 0, vitD: 0.2,
    units: [ { name: "قطعة صغيرة", grams: 50 } ] },

  // ===== شوربة وأطباق =====
  { id: "chicken-soup", name: "شوربة فراخ", cat: "soup", kcal: 35, protein: 3, carbs: 2, fat: 1.5, fiber: 0.2, ca: 8, fe: 0.3, zn: 0.3, vitA: 15, vitC: 0, vitD: 0,
    units: [ { name: "نصف كوب", grams: 120 }, { name: "طبق", grams: 250 } ] },
  { id: "veg-soup", name: "شوربة خضار", cat: "soup", kcal: 40, protein: 1.5, carbs: 7, fat: 1, fiber: 1.8, ca: 25, fe: 0.5, zn: 0.3, vitA: 180, vitC: 8, vitD: 0,
    units: [ { name: "نصف كوب", grams: 120 }, { name: "طبق", grams: 250 } ] },
  { id: "oat-soup", name: "شوربة شوفان بالفراخ", cat: "soup", kcal: 60, protein: 3.5, carbs: 8, fat: 1.8, fiber: 1.2, ca: 20, fe: 0.6, zn: 0.5, vitA: 20, vitC: 1, vitD: 0,
    units: [ { name: "نصف كوب", grams: 120 }, { name: "طبق", grams: 250 } ] },
  { id: "koshari", name: "كشري", cat: "soup", kcal: 165, protein: 6, carbs: 30, fat: 3, fiber: 3.5, ca: 25, fe: 2, zn: 1, vitA: 15, vitC: 3, vitD: 0,
    units: [ { name: "نصف طبق", grams: 150 }, { name: "طبق", grams: 300 } ] },
  { id: "mahshi", name: "محشي (كرنب/كوسة)", cat: "soup", kcal: 130, protein: 3, carbs: 22, fat: 3.5, fiber: 2, ca: 35, fe: 1, zn: 0.6, vitA: 60, vitC: 15, vitD: 0,
    units: [ { name: "قطعة", grams: 60 }, { name: "3 قطع", grams: 180 } ] },
  { id: "moussaka", name: "مسقعة", cat: "soup", kcal: 110, protein: 3, carbs: 10, fat: 7, fiber: 2.5, ca: 25, fe: 0.8, zn: 0.5, vitA: 40, vitC: 8, vitD: 0,
    units: [ { name: "نصف كوب", grams: 100 }, { name: "طبق صغير", grams: 200 } ] },
  { id: "shakshuka", name: "شكشوكة (بيض بالطماطم)", cat: "soup", kcal: 118, protein: 7, carbs: 5, fat: 8, fiber: 1.2, ca: 45, fe: 1.3, zn: 0.9, vitA: 120, vitC: 12, vitD: 1.1,
    units: [ { name: "نصف طبق", grams: 100 }, { name: "طبق", grams: 200 } ] },
];
